### ISSUE TITLE
News Search Bug

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#132]
Steps to reproduce.

1. Search for OSLC3 - 1 post appears
2. Clear search box and select the search button again

Expected:
All posts appear again

Actual
No posts appear

**Comment by jailandrade** [comment]
I let a llitle bug here but now is fixed

**Comment by brianking** [comment]
The bug is still there. Essentially, if I select the Search button any time there is no text in the search box, all posts disappear.

**Comment by jailandrade** [comment]
I submit another patch to this

**Comment by brianking** [comment]
Thanks, works now.
